version: "3.5"
services:
  mongo:
    image: mongo:4.2.0
    restart: always
    container_name: mtx-mongo
    profiles: ["seed", "run"]
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      #MONGODB_DB: ${MONGODB_DB}
      #MONGODB_USER: ${MONGODB_USER}
      #MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./db/data:/data/db
      - ./db/init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - express-mongo
    expose:
      - 27017
  mongoseed:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./db/seed/Dockerfile
    profiles: ["seed"]
    depends_on:
      - mongo
    networks:
      - express-mongo
  app:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: mtx-react-express
    command: npm run dev
    image: vite-react-express:latest
    profiles: ["seed", "run"]
    ports:
      - "3001:3001"
    volumes:
      - ./db/mongoseed.sh:/docker-entrypoint-initdb.d/mongoseed.sh:ro
      - .:/app
      - ./media:/media
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose:
      - 3001
networks:
  express-mongo:
  react-express:
